// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace foodcore.Models
{
    public partial class FoodcoreContext : DbContext
    {
        public FoodcoreContext()
        {
        }

        public FoodcoreContext(DbContextOptions<FoodcoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Mycart> Mycarts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Register> Registers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-CM3D0NO\\SQLEXPRESS;Initial Catalog=foodcore;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Menu>(entity =>
            {
                entity.HasKey(e => e.Itemid)
                    .HasName("PK__menu__56A22C923FE65698");
            });

            modelBuilder.Entity<Mycart>(entity =>
            {
                entity.HasKey(e => e.Cartid)
                    .HasName("PK__mycart__41663FC01EE6EDCC");

                entity.HasOne(d => d.Item)
                    .WithMany(p => p.Mycarts)
                    .HasForeignKey(d => d.Itemid)
                    .HasConstraintName("FK__mycart__itemid__5CD6CB2B");

                entity.HasOne(d => d.UsernameNavigation)
                    .WithMany(p => p.Mycarts)
                    .HasForeignKey(d => d.Username)
                    .HasConstraintName("FK__mycart__Username__5DCAEF64");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.HasOne(d => d.Item)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.Itemid)
                    .HasConstraintName("FK__orders__itemid__4E88ABD4");

                entity.HasOne(d => d.UsernameNavigation)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.Username)
                    .HasConstraintName("FK__orders__username__4D94879B");
            });

            modelBuilder.Entity<Register>(entity =>
            {
                entity.HasKey(e => e.Username)
                    .HasName("PK__register__F3DBC573E7E125A6");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}