// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace foodcore.Models
{
    [Table("orders")]
    public partial class Order
    {
        [Key]
        [Column("orderid")]
        public int Orderid { get; set; }
        [Column("username")]
        [StringLength(20)]
        [Unicode(false)]
        public string Username { get; set; }
        [Column("itemid")]
        [StringLength(20)]
        [Unicode(false)]
        public string Itemid { get; set; }
        [Column("qty")]
        public int? Qty { get; set; }
        [Column("price")]
        public int? Price { get; set; }

        [ForeignKey(nameof(Itemid))]
        [InverseProperty(nameof(Menu.Orders))]
        public virtual Menu Item { get; set; }
        [ForeignKey(nameof(Username))]
        [InverseProperty(nameof(Register.Orders))]
        public virtual Register UsernameNavigation { get; set; }
    }
}